### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by pdavide**
- Ajax requests method changed to GET
- Fixed path in check-node-version.js

### CODE REVIEW

**Comment by srescio** [comment]
beware there are 3 test that will fail as they expected the method call to be POST:
```
 agidSpidEnter
   when script is included in the page
     ✓ should create a module instance in the global scope
   when module instance is available
     init method
       ✓ should return an observable promise for flow control
       ✓ should inject the modal wrapper HTML needed to print the providers popup
       X should fetch italian language if no option was provided, and not provide payload for the providers call
         Expected spy open to have been called with [ 'POST', '/src/data/spidI18n.json' ] but actual calls were [ 'GET', '/src/data/spidI18n.json' ], [ 'GET', '/src/data/spidProviders.json' ]. (1)
       ✓ should NOT inject the modal wrapper HTML more than once
       ✓ should warn the dev if no placeholder is found to render the smartbuttons
       on failure
         ✓ should log failure when ajax calls do not all return data
         ✓ should NOT inject the modal wrapper HTML at all
       when SPID button placeholder are present in the page
         ✓ should render the SPID button if supplied sizes are valid regardless of the case
         ✓ should throw an error if supplied SPID button size is invalid
       when not supplied with a configuration object
         ✓ should add to the active providers the default hidden inputs payload
       when supplied with a configuration object
         X should request the provided language in the config
           Expected spy open to have been called with [ 'POST', '/src/data/spidI18n.json' ] but actual calls were [ 'GET', '/src/data/spidI18n.json' ], [ 'GET', '/src/data/spidProviders.json' ]. (1)
         when provided with a payload
           ✓ should add to the active providers the hidden inputs payload from common
           ✓ should add to the active providers the hidden inputs payload from common and the specific per provider
           ✓ should change the provider input name when specified
           ✓ should ovveride attributes from common when present also in the the provider specific config
     changeLanguage method
       X should call only the i18n endpoint for the new copy
         Expected spy open to have been called with [ 'POST', '/src/data/spidI18n.json' ] but actual calls were [ 'GET', '/src/data/spidI18n.json' ]. (1)
       ✓ should log failure when ajax call does not return data
     updateSpidButtons method
       ✓ should render again the spidbuttons in the placeholders if data was fetched successfully
       ✓ should not render the spidbuttons if providers data was not fetched and throw error
     when a SPID button is clicked
       ✓ should display the provider choice modal
       ✓ should give focus to the displayed modal for accessibility
     when the providers modal is displayed it should allow to close it by
       ✓ click on the top right X button
       ✓ click on the bottom list cancel button
       ✓ hit on the keyboard esc key
     when the informative buttons in the footer are clicked
       ✓ should open the informative modal on top of the providers modal
     when the informative modal is displayed on top of the providers modal it should allow to close it by
       ✓ click on the top right X button in the modal
       ✓ hit on the keyboard esc key
       ✓ should not react to keystrokes different than ESC
     getI18n utility
       ✓ should return the key name when the value cannot be found
     version method
       ✓ should return the semantic version number of the module
     aXe accessibility check (A11y)
       ✓ should not find any violation in the module HTML

32 specs in 0.811s.
>> 3 failures
Warning: Task "jasmine:unitTest" failed. Use --force to continue.
```

**Comment by pdavide** [comment]
It’s ok if I change the test to expect a GET call?

**Comment by srescio** [comment]
Since the resources calls for providers and language were changed to GET yes they should stay consistent with how the code works, strange enough it should have been caught at commit time, anyway when code is finalised a CI step that runs the tests on the repo will be needed

**Comment by srescio** [comment]
Since the resources calls for providers and language were changed to GET yes they should stay consistent with how the code works, strange enough it should have been caught at commit time, anyway when code is finalised a CI step that runs the tests on the repo will be needed

**Pull request merged**
